### ISSUE TITLE
tvgen: support "matrix-style" test vector generation

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/sholva#19]
This is especially handy for testing modules with lots of inputs, but where we only want to test a limited subset of functionality in one test.

Example:

```yaml
  - _description: "different ALU flags affect EFLAGS"
    i_eax: 0x00
    i_ebx: 0x00
    i_ecx: 0x00
    i_edx: 0x00
    i_esi: 0x00
    i_edi: 0x00
    i_esp: 0x00
    i_ebp: 0x00
    i_eip: 0x00
    i_eflags: 0x00
    gpr_selector: 0x00
    gpr_wr: 0x00
    next_eip: 0x00
    alu_wr: 0b1
    alu_flags: [0b000000, 0b110000, 0b110011]
    o_eax: 0x00
    o_ebx: 0x00
    o_ecx: 0x00
    o_edx: 0x00
    o_esi: 0x00
    o_edi: 0x00
    o_esp: 0x00
    o_ebp: 0x00
    o_eip: 0x00
    o_eflags: [0b11111111111111111111001100101110, ...]
```

Each array will have to have the same cardinality, and will be matched pairwise to generate multiple testvectors. So I guess "matrix-style" is a misnomer.
