### ISSUE TITLE
Figure out a testing approach

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/sholva#6]
Testing Verilog modules is a pain, and we don't want to have to hand write + modify large numbers of testbenches.

An idea copied from Slack: a DSL for generating per-module testbenches:

```yaml
foo:
  file: foo.v
  inputs:
    - "[63:0] bar"
    - "[63:0] baz"
  outputs:
    - "[63:0] quux"
  vector: foo.tv
```
